### ISSUE TITLE
能整合 material-ui 么？

### ISSUE THREAD

**Issue by zuohuadong** [skyFi/weapp-native#3]
能整合 material-ui 么？ 应该怎么做？ 还是只能用默认样式？

**Comment by skyFi** [comment]
目前只可以使用material-ui的样式

**Comment by Stupidism** [comment]
wechat 认原生的html标签吗  像div span这些

**Comment by skyFi** [comment]
@Stupidism  不认，但是有 [rich-text](https://mp.weixin.qq.com/debug/wxadoc/dev/component/rich-text.html)可以加载html标签等，也可以使用[web-view](https://mp.weixin.qq.com/debug/wxadoc/dev/component/web-view.html)来加载 h5 页面
