### ISSUE TITLE
工作流改进

### ISSUE THREAD

**Issue by dp199313** [skyFi/weapp-native#6]
在我的理解里cli应该是命令行工具,不应该是一个初始项目或者库
比如下面

```shell
wn create demo
cd demo
yarn
yarn run dev
```

**Comment by skyFi** [comment]
嗯，是这样的。

首先，非常感谢你提出来意见。

原因：项目本身采用的是静态编译，这并不是我理想的使用 React 组件化开发微信小程序的方法，所以没有搭建成严格意义上的命令行工具，如果有这方面的想法的话，可以交流下，如何更好的做这个工作。

**Comment by CXJoyce** [comment]
我也有这方面的疑惑，根据名字以为是一个命令行工具。但是看完感觉这个是一个类react开发小程序吗？标签使用的还是小程序的标签？
