### ISSUE TITLE
该项目不支持webpack吗？

### ISSUE THREAD

**Issue by CXJoyce** [skyFi/weapp-native#7]
请问下该项目没有使用webpack编译吗？我在微信开发者工具中运行时，报regeneratorRuntime is not defined 的错误，按照之前的经验，这个报错应该是Babel配置没有兼容async await，想改下配置，但是没有找到webpack和babelrc文件，请问这个怎么处理？

**Comment by skyFi** [comment]
默认是不支持的，具体的你可以看这里写的 [https://github.com/skyFi/weapp-starter#使用-asyncawait](https://github.com/skyFi/weapp-starter#使用-asyncawait)，这样就可以在小程序中使用async await了。
